replicaCount: 1

image:
  repository: europe-west4-docker.pkg.dev/sensity-350013/id-document-reader/id-document-reader
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []

# licenseKey is provided by sensity and required to run the whole application
licenseKey: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

nodeSelector: {}

tolerations: []

affinity: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  # className is the ingress class for the web ingress (used only in Kubernetes >=v1.19)
  className: ""
  # annotations for the web ingress
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  # hosts is the hostnames or host configuration for the web ingress
  hosts:
    - host: "*"
      paths:
        - path: /id-document-reader
          pathType: Prefix
  # tls will enable TLS termination for the web ingress
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # If you do want to specify resources such us request a GPU, uncomment the
  # following lines, adjust them as necessary, and remove the curly braces after
  # 'resources:'.
  #
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
